server:
  port: 8082

spring:
  jackson:
     property-naming-strategy: SNAKE_CASE


  datasource:
    url: jdbc:postgresql://localhost:5433/tenantDemo
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate

    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        multiTenancy:
          strategy: DISCRIMINATOR
        tenant_identifier_resolver: com.example.TenantIdentifierResolver
    show-sql: true
    generate-ddl: true


  flyway:
    enabled: true
    baseline-on-migration: true
    location: classpath:db/migration


